export interface IResults {
    part_number: string,
    model_name: string,
    [key: string]: string
}
export const mockResults = {
    'company':'Maxon',
    'part_number':'118891',
    'model_name':'EC 32 ‚àö√≤32 mm, brushless, 80 Watt, with Hall sensors',
     'nominal_voltage_in_volts':12.0,
    'thermal_time_constant_in_secs':14.8,
    'nominal_torque_in_mnm':44.6,
    'max_speed_in_rpm':25000.0,
    'speed_torque_gradient_in_rpm_mnm':35.8,
    'speed_constant_in_rpm_v':1280.0,
    'stall_torque_in_mnm':428.0,
    'price':424.41,
    'website':'https://www.maxongroup.com/maxon/view/product/motor/ecmotor/ec/ec32/118891',
    'description':'The electronically commutated EC motors are characterized especially by their favorable torque characteristics,high power, extremely broad speed range and, of course, by their unsurpassed service life.', 
    'chart_id':'64feb01a5bd18370db0d65eb',
    'diameter':'None',
    'length':'None',
    'torque_constant':'None',
    'image_url':'https://www.maxongroup.com/medias/sys_master/root/8845882228766/EC-32-118891-NEW.jpg'
    }

export const sampleData = [
    {
        "id": "US11529390B2",
        "type": "patent",
        "publication_id": "US11529390B2",
        "title": "PCSK9 inhibitory polypolypeptides and methods of use",
        "abstract": "The present invention relates to PCSK9 inhibitors and methods of use thereof. Specifically, the invention relates to PCSK9 cell-based assay, PCSK9 inhibiting polypeptides and derivatives thereof. The invention includes pharmaceutical compositions comprising a PCSK9 inhibitor polypeptide together with a pharmaceutically acceptable carrier and method for treating cardiovascular disorders, hyperlipidemia, inflammatory diseases or inflammatory response to infection.",
        "publication_date": "2022-12-20",
        "www_link": "https://patents.google.com/patent/US11529390B2/en",
        "owner": "INSTITUT DE CARDIOLOGIE DE \n\nMONTREAL",
        "image": "https://api.projectpq.ai/patents/US11529390B2/thumbnails/1",
        "alias": "Poirier et al.",
        "inventors": [
            "Steve Poirier",
            "Gaetan Mayer"
        ],
        "score": 0.039663732051849365,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US20110150875A1",
        "type": "patent",
        "publication_id": "US20110150875A1",
        "title": "EGF-A DOMAIN-MEDIATED MODULATION OF PCKS9 FOR TREATING LIPID DISORDERS",
        "abstract": "The present invention provides, in part, methods and compositions for treating lipid disorders comprising administering a polypeptide that inhibits PCSK9. A novel method for identifying polypeptides that interact with PCSK9 is also provided.",
        "publication_date": "2011-06-23",
        "www_link": "https://patents.google.com/patent/US20110150875A1/en",
        "owner": "Assignee N/A",
        "image": "https://api.projectpq.ai/patents/US20110150875A1/thumbnails/1",
        "alias": "Zhang et al.",
        "inventors": [
            "Qing Zhang",
            "Nicholas J. Murgolo",
            "Joseph A. Hedrick"
        ],
        "score": 0.07116961479187012,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US8206943B1",
        "type": "patent",
        "publication_id": "US8206943B1",
        "title": "Assay for PCSK9 inhibitors",
        "abstract": "The present invention provides methods for identifying modulators of PCSK9, for example, using a variety of assay formats. Inhibitors of PCSK9 can be used for example, to treat diseases such as hyperlipidemia and related disorders.",
        "publication_date": "2012-06-26",
        "www_link": "https://patents.google.com/patent/US8206943B1/en",
        "owner": "Schering Corporation",
        "image": "https://api.projectpq.ai/patents/US8206943B1/thumbnails/1",
        "alias": "Beyer et al.",
        "inventors": [
            "Brian M. Beyer",
            "Thomas Hesson",
            "Hung V. Le",
            "Andrew J. Prongay",
            "Krishna Kalghatgi",
            "Jennifer Joanne Gesell",
            "Richard N. Ingram",
            "Michael R. Ziebell",
            "Brian M. Beyer",
            "Thomas Hesson",
            "Hung V. Le",
            "Andrew J. Prongay",
            "Krishna Kalghatgi",
            "Jennifer Joanne Gesell",
            "Richard N. Ingram",
            "Michael R. Ziebell"
        ],
        "score": 0.08342278003692627,
        "snippet": null,
        "mapping": null,
        "index": "C12Q"
    },
    {
        "id": "US20220072032A1",
        "type": "patent",
        "publication_id": "US20220072032A1",
        "title": "INHIBITORS OF PCSK9 FOR TREATMENT OF LIPOPROTEIN METABOLISM DISORDERS",
        "abstract": "The present disclosure relates to inhibitors of proprotein convertase subtilisin-like/kexin type 9 (PCSK9) for the treatment of lipoprotein metabolism disorders.",
        "publication_date": "2022-03-10",
        "www_link": "https://patents.google.com/patent/US20220072032A1/en",
        "owner": "Aarhus Universitet",
        "image": "https://api.projectpq.ai/patents/US20220072032A1/thumbnails/1",
        "alias": "Gustafsen et al.",
        "inventors": [
            "Camilla Gustafsen",
            "Peder Søndergaard Madsen",
            "Simon Glerup Pedersen"
        ],
        "score": 0.09662169218063354,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US20190177366A1",
        "type": "patent",
        "publication_id": "US20190177366A1",
        "title": "COMPOSITIONS AND METHODS FOR TREATING CARDIOVASCULAR DISEASE",
        "abstract": "The invention provides PCSK9 inhibitors, compositions comprising the PCSK9 inhibitors, and methods of identifying and using the PCSK9 inhibitors.",
        "publication_date": "2019-06-13",
        "www_link": "https://patents.google.com/patent/US20190177366A1/en",
        "owner": "Genentech, Inc.",
        "image": "https://api.projectpq.ai/patents/US20190177366A1/thumbnails/1",
        "alias": "Beresini et al.",
        "inventors": [
            "Maureen Beresini",
            "Daniel Burdick",
            "Charles Eigenbrot, JR.",
            "Daniel Kirchhofer",
            "Robert Lazarus",
            "Wei Li",
            "John Quinn",
            "Nicholas Skelton",
            "Mark Ultsch",
            "Yingnan Zhang"
        ],
        "score": 0.10153108835220337,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US11679146B2",
        "type": "patent",
        "publication_id": "US11679146B2",
        "title": "Compositions and methods for treating pancreatitis",
        "abstract": "The present disclosure provides methods related to inhibiting or treating pancreatitis in a subject in need thereof, which include the use of a proprotein convertase subtilisin kexin 9 (PCSK9) inhibitor. The disclosed PCSK9 inhibitors and compositions including them can be used for treatment, inhibition, or prevention of pancreatitis in a subject. Treatment methods can include administering to the subject a therapeutically effective amount of a PCSK9 inhibitor.",
        "publication_date": "2023-06-20",
        "www_link": "https://patents.google.com/patent/US11679146B2/en",
        "owner": "Anji Pharmaceuticals Inc.",
        "image": "https://api.projectpq.ai/patents/US11679146B2/thumbnails/1",
        "alias": "Meyers et al.",
        "inventors": [
            "Charles D. Meyers",
            "Brian K. Hubbard",
            "Michael H. Serrano-Wu"
        ],
        "score": 0.11978310346603394,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US20170290806A1",
        "type": "patent",
        "publication_id": "US20170290806A1",
        "title": "PCSK9 Inhibitors and Methods of Use Thereof",
        "abstract": "The present invention relates to compositions and methods for treating lipid disorders in a subject. In one embodiment, the compositions of the present invention can be used to inhibit protease proprotein convertase subtilisin-like kexin type 9 (PCSK9). In another embodiment, the compositions of the present invention can be used to disrupt the protein-protein interaction between PCSK9 and low-density lipoprotein receptor (LDLR).",
        "publication_date": "2017-10-12",
        "www_link": "https://patents.google.com/patent/US20170290806A1/en",
        "owner": "Temple University-Of The Commonwealth System of Higher Education",
        "image": "https://api.projectpq.ai/patents/US20170290806A1/thumbnails/1",
        "alias": "Gharbia et al.",
        "inventors": [
            "Magid Abou-Gharbia",
            "Wayne E. Childers"
        ],
        "score": 0.12527626752853394,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US20120219558A1",
        "type": "patent",
        "publication_id": "US20120219558A1",
        "title": "ANTAGONISTS OF PCSK9",
        "abstract": "Antagonists of human proprotein convertase subtilisin-kexin type 9 (PCSK9) are disclosed. Said antagonists are effective in the inhibition of PCSK9 function and thereby provide compositions of matter useful for the treatment of conditions associated with PCSK9 activity. The present invention further discloses nucleic acids encoding PCSK9 antagonists as well as methods of making and using PCSK9 antagonists.",
        "publication_date": "2012-08-30",
        "www_link": "https://patents.google.com/patent/US20120219558A1/en",
        "owner": "Assignee N/A",
        "image": "https://api.projectpq.ai/patents/US20120219558A1/thumbnails/1",
        "alias": "Ni et al.",
        "inventors": [
            "Yan Ni",
            "Ayesha Sitlani",
            "Shilpa Pandit",
            "Dale Lewis",
            "Xun Shen",
            "Sharon Lobo",
            "Timothy McCabe",
            "Jon Condra",
            "Rose Cubbon",
            "Fubao Wang"
        ],
        "score": 0.12666553258895874,
        "snippet": null,
        "mapping": null,
        "index": "C07K"
    },
    {
        "id": "US20110117011A1",
        "type": "patent",
        "publication_id": "US20110117011A1",
        "title": "NEUTRALIZING PROPROTEIN CONVERTASE SUBTILISIN KEXIN TYPE 9 (PCSK9) VARIANTS AND USES THEREOF",
        "abstract": "Neutralizing PCSK9 variants that interact with low density lipoprotein receptor (LDLR) are described. Methods and compositions for treating disorders by administering a pharmaceutically effective amount of a neutralizing PCSK9 variant are described.",
        "publication_date": "2011-05-19",
        "www_link": "https://patents.google.com/patent/US20110117011A1/en",
        "owner": "Assignee N/A",
        "image": "https://api.projectpq.ai/patents/US20110117011A1/thumbnails/1",
        "alias": "Jackson et al.",
        "inventors": [
            "Simon Mark Jackson",
            "Derek Evan Piper"
        ],
        "score": 0.12718766927719116,
        "snippet": null,
        "mapping": null,
        "index": "A61K"
    },
    {
        "id": "US20180066070A1",
        "type": "patent",
        "publication_id": "US20180066070A1",
        "title": "ACETYLATED PCSK9",
        "abstract": "The invention relates to antibodies reactive to acetylated PCSK9, particularly to PCSK9 acetylated in position Lys421, Lys273, Lys69, Lys83, Lys243, Lys258, Lys494, and/or Lys506, and related reagents. The invention also relates to a method of reducing LDL-cholesterol level in a patient in need thereof, said method comprising administering to the subject an effective amount of an antibody binding to acetylated PCSK9. The invention also relates to a method of treating a cholesterol related disorder in a patient in need thereof, said method comprising administering to the subject an effective amount of an antibody binding to acetylated PCSK9. The invention also relates to a method of treating hypercholesterolemia in a patient in need thereof, said method comprising administering to the subject an effective amount of an antibody binding to acetylated PCSK9.",
        "publication_date": "2018-03-08",
        "www_link": "https://patents.google.com/patent/US20180066070A1/en",
        "owner": "UNIVERSITAT ZURICH",
        "image": "https://api.projectpq.ai/patents/US20180066070A1/thumbnails/1",
        "alias": "MIRANDA et al.",
        "inventors": [
            "Melroy Xavier MIRANDA",
            "Thomas F. LUSCHER"
        ],
        "score": 0.12960922718048096,
        "snippet": null,
        "mapping": null,
        "index": "C07K"
    }
]